export const normalLeaves = [
  {
    id: 'leaf01',
    url: null,
    flipX: false,
    flipY: false,
    reverse: false,
    scrub: 3,
    start: '300px top',
    end: 'bottom top',
    width: 1023,
    height: 760,
    transform: {
      x: 100,
      y: -200,
      rotateZ: 10,
    },
    position: {
      top: -250,
      right: -300,
    },
    mobile: {
      position: { top: -100, right: -150 },
      start: '120px top',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf02',
    url: null,
    flipX: false,
    flipY: false,
    reverse: true,
    scrub: 3,
    start: 'top 350px',
    end: 'bottom top',
    width: 1023,
    height: 760,
    transform: {
      x: 100,
      y: -300,
    },
    position: {
      top: 400,
      left: -700,
    },
    mobile: {
      position: { top: 500, left: -300 },
      start: 'top 580px',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf03',
    url: null,
    flipX: false,
    flipY: false,
    reverse: false,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    width: 1023,
    height: 760,
    transform: {
      x: -50,
      y: -500,
    },
    position: {
      top: 2500,
      right: -630,
    },
    mobile: {
      position: { top: 2300, right: -330 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf04',
    url: null,
    flipX: true,
    flipY: false,
    reverse: false,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    width: 1023,
    height: 760,
    transform: {
      x: 100,
      y: -500,
      rotateZ: -5,
    },
    position: {
      top: 4000,
      left: -800,
    },
    mobile: {
      position: { top: 3500, left: -380 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf05',
    url: null,
    flipX: false,
    flipY: false,
    reverse: true,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    width: 1023,
    height: 760,
    transform: {
      x: 100,
      y: -300,
    },
    position: {
      top: 4900,
      left: -700,
    },
    mobile: {
      position: { top: 4200, left: -350 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf06',
    url: null,
    flipX: true,
    flipY: false,
    reverse: false,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    width: 1023,
    height: 760,
    position: {
      top: 7800,
      left: -700,
    },
    transform: {
      x: 50,
      y: -500,
    },
    mobile: {
      position: { top: 6200, left: -320 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf07',
    url: null,
    flipX: false,
    flipY: true,
    reverse: false,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    width: 1023,
    height: 760,
    position: {
      top: 9200,
      right: -500,
    },
    transform: {
      x: 100,
      y: -500,
    },
    mobile: {
      position: { top: 7200, right: -250 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf08',
    url: null,
    flipX: false,
    flipY: false,
    reverse: true,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    width: 1023,
    height: 760,
    position: {
      top: 10500,
      left: -600,
    },
    transform: {
      x: 80,
      y: -300,
    },
    mobile: {
      position: { top: 7900, left: -300 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
]

export const flatLeaves = [
  {
    id: 'leaf09',
    url: 'assets/images/euca-base.png',
    flipX: false,
    flipY: false,
    reverse: false,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    width: 1023,
    height: 760,
    transform: {
      x: 100,
      y: -500,
      rotateZ: -5,
    },
    position: {
      top: 1000,
      left: -400,
    },
    mobile: {
      position: { top: 900, right: -200 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf10',
    url: 'assets/images/euca-base.png',
    flipX: false,
    flipY: false,
    reverse: true,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    width: 1023,
    height: 760,
    transform: {
      x: 100,
      y: -300,
    },
    position: {
      top: 2800,
      left: -300,
    },
    mobile: {
      position: { top: 2500, left: -250 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf11',
    url: 'assets/images/euca-base.png',
    flipX: false,
    flipY: false,
    reverse: false,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    width: 1023,
    height: 760,
    position: {
      top: 4800,
      right: -500,
    },
    transform: {
      x: -50,
      y: -1000,
    },
    mobile: {
      position: { top: 4400, right: -320 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
]

export default [...normalLeaves, ...flatLeaves]
