export default [
  {
    id: 'leaf01',
    url: null,
    flipX: false,
    flipY: false,
    reverse: false,
    scrub: 3,
    start: '300px top',
    end: 'bottom top',
    transform: {
      x: 100,
      y: -200,
      rotateZ: 10,
    },
    position: {
      top: -250,
      right: -300,
    },
    mobile: {
      position: { top: -100, right: -150 },
      start: '120px top',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf02',
    url: null,
    flipX: false,
    flipY: false,
    reverse: true,
    scrub: 3,
    start: 'top 350px',
    end: 'bottom top',
    transform: {
      x: 100,
      y: -300,
    },
    position: {
      top: 400,
      left: -700,
    },
    mobile: {
      position: { top: 600, left: -300 },
      start: 'top 580px',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf03',
    url: null,
    flipX: false,
    flipY: false,
    reverse: false,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    transform: {
      x: -50,
      y: -500,
    },
    position: {
      top: 2500,
      right: -630,
    },
    mobile: {
      position: { top: 2300, right: -330 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf04',
    url: null,
    flipX: true,
    flipY: false,
    reverse: false,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    transform: {
      x: 100,
      y: -500,
      rotateZ: -5,
    },
    position: {
      top: 4000,
      left: -800,
    },
    mobile: {
      position: { top: 3500, left: -400 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf05',
    url: null,
    flipX: false,
    flipY: false,
    reverse: true,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    transform: {
      x: 100,
      y: -300,
    },
    position: {
      top: 4900,
      left: -700,
    },
    mobile: {
      position: { top: 4200, left: -350 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf06',
    url: null,
    flipX: true,
    flipY: false,
    reverse: false,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    position: {
      top: 7800,
      left: -700,
    },
    transform: {
      x: 50,
      y: -500,
    },
    mobile: {
      position: { top: 6200, left: -320 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf07',
    url: null,
    flipX: false,
    flipY: true,
    reverse: false,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    position: {
      top: 9200,
      right: -500,
    },
    transform: {
      x: 100,
      y: -500,
    },
    mobile: {
      position: { top: 7200, right: -250 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
  {
    id: 'leaf08',
    url: null,
    flipX: false,
    flipY: false,
    reverse: true,
    scrub: 3,
    start: 'top bottom',
    end: 'bottom top',
    position: {
      top: 10500,
      left: -600,
    },
    transform: {
      x: 80,
      y: -300,
    },
    mobile: {
      position: { top: 7900, left: -300 },
      start: 'top bottom',
      end: 'bottom top',
    },
  },
]
